# This is the data configuration file, holds settings for jekyll ot refer to when building.

# set the default values fore future posts
defaults:
  _

    scope:
      path: "_posts" # empty string mean applies to all files
      type: "posts"
    values:
      layout: "blog_entry"
      author: "Sooham Rafiz"


